### ISSUE TITLE
Many errors in HockeySDK

### ISSUE THREAD

**Issue by JamesNK** [bitstadium/HockeySDK-Windows#119]
This error from the HockeySDK has occurred 63 times in the last 2 days in our application:

```
ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds. 

at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity) at System.Collections.Generic.Queue`1.Enqueue(T item)
at Microsoft.HockeyApp.HockeyClient.Track(ITelemetry telemetry) at Microsoft.HockeyApp.HockeyClient.TrackDependency(DependencyTelemetry telemetry)
```

**Comment by TroubleMakerBen** [comment]
There will be a new release in early 2018 that includes this.
