### ISSUE TITLE
Desktop to UWP Bridge - WPF application

### ISSUE THREAD

**Issue by johnmurphy01** [bitstadium/HockeySDK-Windows#121]
I am converting a Win32 WPF application to a Windows 10 store app using the Desktop to UWP Bridge process. The conversion succeeds and installs. However, when I try to launch my application, the app crashes. EventViewer tells me the following:

```
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.HockeyApp.HockeyPlatformHelperWPF.get_AppPackageName()
   at Microsoft.HockeyApp.HockeyClient.get_PrefilledCrashLogInfo()
   at Microsoft.HockeyApp.HockeyClient.HandleException(System.Exception)
   at Microsoft.HockeyApp.HockeyClientWPFExtensions.Current_DispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)
   at System.Windows.Threading.Dispatcher.CatchException(System.Exception)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(System.Object, System.Exception)
   at System.Windows.Threading.ExceptionWrapper.CatchException(System.Object, System.Exception, System.Delegate)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
```

This doesn't tell me much but running off the assumption that something is wrong with HockeyApp, I commented out the initialization code. After doing this, the application runs with no problems.

My question, can HockeySDK.WPF NuGet package be run whenever the app is converted using the Desktop to UWP Bridge process? If not, is there a way to use HockeyApp whenever the app is both a WPF application and a Windows 10 store application?

**Comment by edoust** [comment]
Could you get this to work?

**Comment by elamalani** [comment]
@johnmurphy01 @edoust We have never tested HockeySDK to work by converting a WPF application to a UWP app using the Desktop to UWP Bridge process. I am curious to know if it worked out for you at all?

**Comment by johnmurphy01** [comment]
We have yet to deploy the Desktop bridge converted version of our application but last I checked, this did not work giving the above exception. Will there be/is there now support for this?

**Comment by elamalani** [comment]
@johnmurphy01 This feature is not on our roadmap to support in HockeyApp. I will tag this issue as a feature request for now but we are very open to community contribution if you'd like to submit a PR for a fix. Thank you!

**Comment by bmourat** [comment]
Hi @johnmurphy01

Are you converting msi, setup, or plain executable without setup file? I've tried converting today simple wpf app and it worked fine with various hockeyapp usage scenarios. Or maybe you are performing something special during startup, could you please elaborate on this?

Murat
