### ISSUE TITLE
UWP resume exception in Lumia devices

### ISSUE THREAD

**Issue by poumason** [bitstadium/HockeySDK-Windows#131]
I report the issue.
The UWP app integrated the HockeyApp SDK (4.1.6)  and run app on the Lumia 930 (Win10 14393+).
When app into the OnResuming(), the HockeyApp be happened the exception.
The stack trace:
```text
   at System.IO.Compression.Deflater.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.Deflater..ctor(CompressionLevel compressionLevel, Int32 windowBits)
   at System.IO.Compression.DeflateStream.InitializeDeflater(Stream stream, Boolean leaveOpen, Int32 windowBits, CompressionLevel compressionLevel)
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits)
   at Microsoft.HockeyApp.Services.HttpClientTransmission.CreateCompressedStream(Stream stream)
   at Microsoft.HockeyApp.Extensibility.Implementation.JsonSerializer.Serialize(IEnumerable`1 telemetryItems, Boolean compress)
   at Microsoft.HockeyApp.Channel.FlushManager.Flush()
   at Microsoft.HockeyApp.Channel.PersistenceChannel.Flush()
   at Microsoft.HockeyApp.Extensibility.Windows.SessionTelemetryModule.TrackSessionState()
   at Microsoft.HockeyApp.Extensibility.Windows.SessionTelemetryModule.<HandleApplicationStartedEvent>b__15_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.HockeyApp.Extensibility.Windows.SessionTelemetryModule.<HandleApplicationStartedEvent>d__15.MoveNext()
```

**Comment by bmourat** [comment]
Hi @poumason 

Does this happen only on Lumia devices? Did you try other devices with Win10 14393?

**Comment by MatkovIvan** [comment]
Looks like related to #112

What version of `Microsoft.NETCore.UniversalWindowsPlatform` in your project?
Do you use `EntityFrameworkCore.Sqlite`?
