### ISSUE TITLE
'There are no more files'

### ISSUE THREAD

**Issue by jgcoded** [bitstadium/HockeySDK-Windows#135]
Whenever I run my WPF app I get this exception in the call to `HockeyClient.Current.Configure.SendCrashesAsync()`: `System.IO.IOException: 'There are no more files.`

This is the value of the maybeFullPath variable at the top of the stack:
`HockeyCrashes\CE-BF-A7-1E-54-C7-5A-B7-C2-FC-0B-EA-EF-03-6A-59\crashinfo_*.log`

```
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.IsolatedStorage.IsolatedStorageFile.GetFileDirectoryNames(String path, String userSearchPattern, Boolean file)
   at System.IO.IsolatedStorage.IsolatedStorageFile.GetFileNames(String searchPattern)
   at Microsoft.HockeyApp.HockeyPlatformHelperWPF.<GetFileNamesAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.HockeyApp.HockeyClient.<GetCrashFileNamesAsync>d__103.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.HockeyApp.HockeyClient.<AnyCrashesAvailableAsync>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.HockeyApp.HockeyClientWPFExtensions.<SendCrashesAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

In order to work around this I've written my call to send crashes async like this:
```
try
{
    await HockeyClient.Current.SendCrashesAsync();
}
catch (Exception ex)
{
    // ...
}
```

I'm using HockeySDK.WPF v4.1.6

**Comment by TroubleMakerBen** [comment]
Hi @jgcoded,

thx for getting in touch and the inconvenience this causes. We're looking at this and I'll update the ticket accordingly.

Best,
Benjamin

**Comment by bmourat** [comment]
Hi @jgcoded 

Your path seems to be right. Seems like IsolatedStorage is throwing this error which is strange. Analyzing information in this issue and issue #136 there is something unique in your project setup that is causing this two errors. So could you please provide more info on how is your project setup, what other dependencies you are using and everything that might help to localize the root of these problems.

Thanks,
Murat

**Comment by jgcoded** [comment]
Thanks for getting back to me Murat. My project is setup as a wpf app that gets converted to a uwp app with the Desktop Bridge tool. The issue only occurred when I was debugging the Desktop Bridge version of the app in VS 2017. Release mode didn't throw these exceptions.

I don't use HockeySDK anymore, but at that time my only other dependency was StructureMap iirc.
