### ISSUE TITLE
Calling TrackException throws KeyNotFoundException

### ISSUE THREAD

**Issue by ridomin** [bitstadium/HockeySDK-Windows#153]
When calling `Microsoft.HockeyApp.HockeyClient.Current.TrackException(ex);` I got

```
System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key was not present in the dictionary.
  Source=mscorlib
  StackTrace:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.HockeyApp.ServiceLocator.GetService[T]()
   at Microsoft.HockeyApp.HockeyClient.TrackException(Exception exception, IDictionary`2 properties)
   at BackToTheFuture.Analytics.TrackException(Exception ex) in C:\code\BackToTheFuture\BackToTheFuture.Wpf\MainWindow.xaml.cs:line 23
   at BackToTheFuture.MainWindow.TabItem_Loaded_1(Object sender, RoutedEventArgs e) in C:\code\BackToTheFuture\BackToTheFuture.Wpf\MainWindow.xaml.cs:line 62
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by achocron** [comment]
Can you please share the code you use to start the Hockey SDK? Also, can you share any console logs that HockeyApp prints? Feel free to redact app ID or any other sensitive fields.

**Comment by ridomin** [comment]
you can see the initialization [here](https://github.com/ridomin/BackToTheFuture/blob/master/BackToTheFuture.Wpf/App.xaml.cs#L26) , also the full repro.

I tried to use the overloaded constructor but it was not available #152

**Comment by achocron** [comment]
Thanks for that. Out of curiosity, why are you creating a TrackException method yourself rather than using the provided `TrackException` method? https://github.com/bitstadium/HockeySDK-Windows/blob/4a18ef84c951922a7695857e75b44a7719881c45/Src/Kit.Core45/HockeyClient.cs#L973

**Comment by ridomin** [comment]
that's the point of this issue, calling TrackException fails with the stack provided

**Comment by thyeggman** [comment]
Hi @ridomin - After some investigation, it appears `ClassicCOM.dll` was compiled for x86 (32-bit) processors, and that's why you're getting the exception.  If you're running on a 64-bit machine, it probably won't work.  I don't know the history of this project or if it has worked in the past, but this seems like the reason why you're getting the exception.

The HockeyApp SDK should still prevent the crash in this case, but note that it may not be reported ([see item 3.3](https://support.hockeyapp.net/kb/client-integration-windows-and-windows-phone/how-to-instrument-applications-on-windows-for-crash-reporting)).  I'll look into it more tomorrow.  In the meantime, if you have the ability to recompile the dll, could you try that?

As an FYI, since HockeyApp is being deprecated, we do have WPF platform support on the App Center [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#platform-support) (see also [this issue](https://github.com/Microsoft/appcenter/issues/118)).

**Comment by thyeggman** [comment]
Hi @ridomin - following up here.  It appears the crash is happening too close to start for HockeyApp to catch it.  Are you able to get a version of ClassicCom.dll compiled for your architecture?

**Comment by thyeggman** [comment]
I've closed this issue.  If you can provide more information or still need help please don't hesitate to reach out!

**Comment by thyeggman** [comment]
I talked with my co-worker @ElektrojungeMS and it looks like there might still be an issue with the SDK.  We'll get back to you if we end up finding anything.  I've reopened the issue as well.

**Comment by annakocheshkova** [comment]
Confirm this is a bug. We need to add a safer way to retrieve service.

**Comment by devperson** [comment]
Any updates on this, I'm getting same exception when calling TrackException method.

**Comment by elamalani** [comment]
Hi there, this is a known bug but unfortunatately, we have prioritized not to fix the issue in the SDK as we are actively working on [App Center](https://appcenter.ms) which is the next generation product of HockeyApp. I'd recommend you to please fork the SDK and fix this issue.
